main: fr.lunki.mapgenerator.MapGenerator
name: MapGenerator
version: 1.1
api-version: 1.13
author: Lunki51
commands:
  getcustommap:
    description: GET MAPS EASY
  addicon:
    description: ADD ICON TO A MAP
